controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\Applications;
use app\models\IntakeRequirements;
use app\models\ApplicantRequirements;
use app\models\ApplicationPayments;
use app\models\ContactForm;
use yii\data\ActiveDataProvider;
use yii\base\Model;
use yii\web\UploadedFile;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use Exception;

class SiteController extends Controller
{
    public $enableCsrfValidation = false;
    
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public $layout = 'home';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/applications']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Creates a new Applications model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionApplyNow()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $model = new Applications();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                Yii::$app->session->setFlash('success','Details saved successfully. Please confirm to proceed!');
                return $this->redirect(['update', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('apply-now', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Applications model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $model = Applications::findOne($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success','Please attach required documents!');
            return $this->redirect(['add-requirements', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionMakePayment($id)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $callBackUrl = Url::to(['payment-confirmation','id'=>$id],true);
        $model = Applications::findOne($id);
        $payment = new ApplicationPayments();
        if ($this->request->isPost && $payment->load($this->request->post()) ) {
            $myValues = Yii::$app->request->post("ApplicationPayments");
            $schoolCode = '101';
            $password = 'SeetaApi';
            $hash = md5($schoolCode.$id.$password);
            $post = [
                'amount' => $myValues['amount'],
                'externalReference' => $id,
                'firstName'   => $myValues['first_name'],
                'middleName'   => $myValues['middle_name'],
                'lastName'   => $myValues['last_name'],
                'reason'   => $myValues['reason'],
                'phoneNumber'   => $myValues['phone_number'],
                'callBackUrl'   => $callBackUrl,
            ];

            $curl = curl_init();
            curl_setopt_array($curl, array(
            CURLOPT_URL => 'https://schoolpaytest.servicecops.com/uatpaymentapi/AndroidRS/AdhocPayments/Request/'.$schoolCode.'/'.$hash,
            CURLOPT_SSLCERT => Yii::getAlias('@app') .'/certificates/cert.cer',
            CURLOPT_SSLKEY => Yii::getAlias('@app') .'/certificates/private.pem',
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_ENCODING => '',
            CURLOPT_MAXREDIRS => 10,
            CURLOPT_TIMEOUT => 0,
            CURLOPT_FOLLOWLOCATION => true,
            CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
            CURLOPT_CUSTOMREQUEST => 'POST',
            CURLOPT_POSTFIELDS => json_encode($post),
            CURLOPT_HTTPHEADER => array(
                'Content-Type: application/json'
            ),
            ));

            $response = curl_exec($curl);
            if ($response === false) {
                throw new Exception(curl_error($curl), curl_errno($curl));
            }
            curl_close($curl);
            $data = json_decode($response, true);
            if($data['returnCode'] == 0){
                $payment->application_id = $id;
                $payment->status = $data['status'];
                if(!$payment->save()){
                    print_r($payment->getFirstErrors());
                }
                $model->status = 'Submitted Payment';
                $model->save(false);
                $mailer = Yii::$app->mailer;
                $message = $mailer->compose('new-application-html')
                    ->setTo([Yii::$app->params['adminEmail']])      // or just $user->email
                    ->setFrom([Yii::$app->params['senderEmail'] => Yii::$app->params['senderName']])
                    ->setReplyTo(Yii::$app->params['senderEmail'])
                    ->setSubject('New Application')
                    ->send();
                Yii::$app->session->setFlash('success','Please hold on while your payment is being processed!');
                return $this->redirect(['payment-confirmation','id'=>$id]);    
            }else{
                Yii::$app->session->setFlash('error',$data['returnMessage']);
            }
        }

        return $this->render('make-payment', [
            'model' => $model,
            'payment' => $payment,
        ]);
    }

    public function actionPaymentConfirmation($id)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $model = Applications::findOne($id);
        $payment = ApplicationPayments::findOne(['application_id' => $id]);
        if ($this->request->isPost){
            $post = json_decode($this->request->getRawBody());
            if($post->returnCode == 0){
                $payment->status = 'PAID';
                $payment->save(false);   
                return $this->asJson([
                    'returnCode' => 0,
                    'status' => 'PAID'
                ]); 
            }
        }
        return $this->render('payment-confirmation', [
            'model' => $model,
            'payment' => $payment,
        ]);
    }

    public function actionPaymentStatus($id){
        $payment = ApplicationPayments::findOne(['application_id' => $id]);
        return json_encode($payment->status);
    }

    public function actionAddRequirements($id)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['/applications']);
        }
        $model = Applications::findOne($id);
        $requirements = IntakeRequirements::find()->where(['intake_id'=>$model->intake_id])->all();
        $dataProvider = new ActiveDataProvider([
            'query' => ApplicantRequirements::find()->where(['application_id'=>$id])
        ]);

        if (Model::loadMultiple($requirements, Yii::$app->request->post()) && Model::validateMultiple($requirements)) {
            foreach ($requirements as $index => $requirement) {

views/layouts/home.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\HomeAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;

HomeAsset::register($this);
?>
<?php $this->beginPage() ?>

<!doctype html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta name="author" content="Ecology Theme">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="shortcut icon" href="<?=Url::to('@web/images/favicon.ico', true); ?>" type="image/x-icon">
    <!-- Goole Font -->
    <link href="https://fonts.googleapis.com/css?family=Rubik:400,500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<header class="header_four">
<!-- Preloader -->
<div id="preloader">
    <div id="status">&nbsp;</div>
</div>    
    <div class="header_top">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-lg-12">
                    <div class="info_wrapper">
                        <div class="contact_info">                   
        					<ul class="list-unstyled">
                                <li><i class="flaticon-phone-receiver"></i>+256-700-460-055</li>
        						<li><i class="flaticon-mail-black-envelope-symbol"></i>admin@seeta.com</li>
        					</ul>                    
                        </div>
                        <div class="login_info">
                             <ul class="d-flex">
                                <li class="nav-item"><a href="<?=Url::to('/site/login',true); ?>" class="nav-link join_now js-modal-show"><i class="flaticon-padlock"></i>Log In</a></li>
                            </ul>
                            <a href="<?=Url::to('/site/apply-now'); ?>" title="" class="apply_btn">Apply Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="edu_nav">
        <div class="container">
            <nav class="navbar navbar-expand-md navbar-light bg-faded">
                <a class="navbar-brand" href="<?=Url::to('/site/index'); ?>">
                    <img src="<?=Url::to('@web/images/logo.png', true); ?>"/>
                </a>
                <div class="collapse navbar-collapse main-menu" id="navbarSupportedContent">
                    <ul class="navbar-nav nav lavalamp ml-auto menu">
                        <li class="nav-item"><a href="<?=Url::to('/site/index'); ?>" class="nav-link active">Home</a></li>
                        <li class="nav-item"><a href="<?=Url::to('/site/about'); ?>" class="nav-link">About</a></li>
                        <li class="nav-item"><a href="/site/index#ourevents" class="nav-link">Events</a></li>
                        <li class="nav-item"><a href="/site/index#ourblog" class="nav-link">Blog</a></li>
                        <li class="nav-item"><a href="/site/index#alumni" class="nav-link">Alumni</a></li>     
                        <li class="nav-item"><a href="<?=Url::to('/site/contact'); ?>" class="nav-link">Contact</a></li>
                    </ul>
                </div>
                <div class="mr-auto search_area ">
                    <ul class="navbar-nav mx-auto">
                        <li class="nav-item"><i class="search_btn flaticon-magnifier"></i>
                            <div id="search">
                                <button type="button" class="close">×</button>
                                 <form>
                                     <input type="search" value="" placeholder="Search here...."  required/>
                                 </form>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav><!-- END NAVBAR -->
        </div> 
    </div>


    <!--==================
        Slider
    ===================-->

</header> <!--  End header section-->
<div class="container">
<?= Breadcrumbs::widget([
    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
]) ?>
<?= Alert::widget() ?>
</div>
<?= $content ?>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-3 col-md-3 col-lg-3 p-0 ">
                <div class="shape_wrapper">
                    <img src="<?=Url::to('@web/images/shapes/bubble_shpe_1.png', true); ?>" alt="" class="shape_t_1"> 
                    <img src="<?=Url::to('@web/images/shapes/round_shpae_1.png', true); ?>" alt="" class="shape_t_2">
                </div>   
            </div>
            <div class="col-12 col-sm-9 col-md-9 col-lg-9 p-0 become_techer_wrapper">
                <div class="become_a_teacher">
                    <div class="title">
                        <h2>Become A Student</h2>
                        <p>Lorem ipsum dolor sit amet mollis felis dapibus arcu donec viverra. Pede phasellus eget. Etiam maecenas vel vici quis dictum rutrum nec nisi et.</p>  
                    </div><!-- ends: .section-header -->
                    <div class="get_s_btn">
                        <a href="/site/apply-now" title="">Apply Now</a>
                    </div>
                    <img src="<?=Url::to('@web/images/shapes/bubble_shpe_2.png', true); ?>" alt="" class="shape_t_1"> 
                </div>                                
            </div>
        </div>
        <div class="footer_top">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="footer_single_col footer_intro">
                        <img src="<?=Url::to('@web/images/logo2.png', true); ?>" alt="" class="f_logo"> 
                        <p>Ante amet vitae vulputate odio nulla vel pretium pulvinar aenean. Rhoncus eget adipiscing etiam arcu. Ultricies justo ipsum nec amet.</p>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    <div class="footer_single_col">
                        <h3>Useful Links</h3>
                        <ul class="location_info quick_inf0">
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Developers</a></li>
                            <li><a href="#">Services</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>                         
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-2">
                    <div class="footer_single_col information">
                        <h3>information</h3>
                        <ul class="quick_inf0">
                            <li><a href="#">Campus Tour</a></li>
                            <li><a href="#">Student Life</a></li>
                            <li><a href="#">Scholarship</a></li>
                            <li><a href="#">Admission</a></li>
                            <li><a href="#">Leadership</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <div class="footer_single_col contact">
                        <h3>Contact Us</h3>
                        <p>Fell free to get in touch us via Phone or send us a message.</p>
                        <div class="contact_info">
                            <span>+256 700-460-055</span> 
                            <span class="email">admin@seeta.com</span>
                        </div>
                        <ul class="social_items d-flex list-unstyled">
                            <li><a href="#"><i class="fab fa-facebook-f fb-icon"></i></a></li>
                            <li><a href="#"><i class="fab fa-twitter twitt-icon"></i></a></li>
                            <li><a href="#"><i class="fab fa-linkedin-in link-icon"></i></a></li>
                            <li><a href="#"><i class="fab fa-instagram ins-icon"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="round_shape">
        <span class="shape_1"></span> 
        <span class="shape_2"></span> 
        <span class="shape_3"></span> 
        <span class="shape_4"></span> 
        <span class="shape_5"></span> 
        <span class="shape_6"></span>
    </div>
    <img src="<?=Url::to('@web/images/shapes/footer_bg_shpe_1.png', true); ?>" alt="" class="shapes1_footer"> 
</footer><!-- End Footer -->

<section id="scroll-top" class="scroll-top">
    <h2 class="disabled">Scroll to top</h2>
    <div class="to-top pos-rtive">
        <a href="#"><i class = "flaticon-right-arrow"></i></a>
    </div>
</section>

<?php $this->endBody() ?>
</body>


</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\widgets\Alert;
use yii\bootstrap4\Breadcrumbs;
use yii\bootstrap4\Html;
use yii\bootstrap4\Nav;
use yii\bootstrap4\NavBar;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>" class="h-100">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="<?=Url::to('@web/images/favicon.ico', true); ?>" type="image/x-icon">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <?php $this->head() ?>
</head>
<body class="d-flex flex-column h-100">
<?php $this->beginBody() ?>

<header>
    <?php
    NavBar::begin([
        'brandLabel' => 'Seeta Online',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar navbar-expand-md navbar-dark bg-dark fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav ml-auto'],
        'items' => [
            ['label' => 'Home', 'url' => ['/site/index'],'visible' => Yii::$app->user->isGuest],
            ['label' => 'About', 'url' => ['/site/about'],'visible' => Yii::$app->user->isGuest],
            ['label' => 'Contact', 'url' => ['/site/contact'],'visible' => Yii::$app->user->isGuest],
            ['label' => 'Applications', 'url' => ['/applications'], 'visible' => !Yii::$app->user->isGuest],
            ['label' => 'Intakes', 'url' => ['/intakes'], 'visible' => !Yii::$app->user->isGuest],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => ['/site/login']]
            ) : (
                '<li>'
                . Html::beginForm(['/site/logout'], 'post', ['class' => 'form-inline'])
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->username . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>
</header>

<main role="main" class="flex-shrink-0">
    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</main>

<footer class="footer mt-auto py-3 text-muted">
    <div class="container">
        <p class="float-left">&copy; My Company <?= date('Y') ?></p>
        <!-- <p class="float-right"><?= Yii::powered() ?></p> -->
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>