models/Applications.php
<?php

namespace app\models;

use Yii;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "applications".
 *
 * @property int $id
 * @property int $intake_id
 * @property string $name
 * @property string $dob
 * @property string $gender
 * @property string $religion
 * @property string $nationality
 * @property string $home_address
 * @property string|null $guardian_name
 * @property string|null $guardian_occupation
 * @property string|null $guardian_contact
 * @property string|null $created_at
 * @property string|null $updated_at
 */
class Applications extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'applications';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['intake_id', 'name', 'dob', 'gender', 'religion', 'nationality', 'home_address'], 'required'],
            [['intake_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['status','name', 'dob', 'gender', 'religion', 'nationality', 'home_address', 'guardian_name', 'guardian_occupation', 'guardian_contact'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'intake_id' => 'Intake',
            'name' => 'Name',
            'dob' => 'Dob',
            'gender' => 'Gender',
            'religion' => 'Religion',
            'nationality' => 'Nationality',
            'home_address' => 'Home Address',
            'guardian_name' => 'Guardian Name',
            'guardian_occupation' => 'Guardian Occupation',
            'guardian_contact' => 'Guardian Contact',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function getIntake(){
        return $this->hasOne(Intakes::classname(), ['id'=>'intake_id']);
    }
}

controllers/ApplicationsController.php
<?php

namespace app\controllers;

use app\models\Applications;
use app\models\ApplicantRequirements;
use app\models\ApplicationPayments;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ApplicationsController implements the CRUD actions for Applications model.
 */
class ApplicationsController extends Controller
{
    /**
     * @inheritDoc
     */
    public function behaviors()
    {
        return array_merge(
            parent::behaviors(),
            [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['POST'],
                    ],
                ],
            ]
        );
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Applications::find(),
            'pagination' => [
                'pageSize' => 5
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Applications model.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $requirements = ApplicantRequirements::find()->where(['application_id'=>$id]);
        $payments = ApplicationPayments::find()->where(['application_id'=>$id]);
        $reqProvider = new ActiveDataProvider([
            'query' => $requirements
        ]);
        $payProvider = new ActiveDataProvider([
            'query' => $payments
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id),
            'reqProvider' => $reqProvider,
            'payProvider' => $payProvider,
        ]);
    }

    /**
     * Creates a new Applications model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Applications();

        if ($this->request->isPost) {
            if ($model->load($this->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $model->loadDefaultValues();
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Applications model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($this->request->isPost && $model->load($this->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Applications model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param int $id ID
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Applications model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param int $id ID
     * @return Applications the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Applications::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/DownloadController.php
<?php

namespace app\controllers;

use yii\web\NotFoundHttpException;

class DownloadController extends \yii\web\Controller
{
    public function actionIndex($file)
    {
        $filepath = \Yii::getAlias('@app')."/uploads/" . $file;

        // Process download
        if(file_exists($filepath)) {
            //header('Content-Description: File Transfer');
            header('Content-Type: application/pdf');
            header('Content-Disposition: attachment; filename="'.basename($filepath).'"');
            header('Expires: 0');
            header('Cache-Control: must-revalidate');
            header('Pragma: public');
            header('Content-Length: ' . filesize($filepath));
            //flush(); // Flush system output buffer
            readfile($filepath);
            return;
        }else{
            throw new NotFoundHttpException('The requested file does not exist.');
        }
        return $this->render('index');
    }
}

views/applications/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="applications-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'intake_id')->textInput() ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'dob')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'gender')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'religion')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'nationality')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'home_address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'guardian_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'guardian_occupation')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'guardian_contact')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/applications/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Create Applications';
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="applications-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/applications/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Applications';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="applications-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            // 'id',
            'name',
            'intake.name:text:Intake',
            'dob',
            'gender',
            //'religion',
            //'nationality',
            //'home_address',
            //'guardian_name',
            //'guardian_occupation',
            //'guardian_contact',
            //'status',
            'created_at',
            //'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}'
            ],
        ],
    ]); ?>


</div>

views/applications/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = 'Update Applications: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="applications-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/applications/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Applications', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="applications-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="row">
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'name',
                    'intake.name:text:Intake',
                    'dob',
                    'gender',
                    'religion',
                    'nationality',
                    'home_address',
                    'guardian_name',
                    'guardian_occupation',
                    'guardian_contact',
                    'status',
                    'created_at',
                    'updated_at',
                ],
            ]) ?>
        </div>
        <div class="col-md-6">
            <h3>Required Documents</h3>
            <?= GridView::widget([
                'dataProvider' => $reqProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'requirement.name',
                    [
                        'label' => 'Attachment',
                        'value' => function($data){
                            return Html::a('download file',['/download/index','file'=>$data->attachment]);
                        },
                        'format' => 'raw'
                    ],
                    'created_at',
                ],
            ]); ?>
            <h3>Payment Details</h3>
            <?= GridView::widget([
                'dataProvider' => $payProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'amount',
                    'status',
                    'phone_number',
                    'created_at:text:Date'
                ],
            ]); ?>

        </div>
    </div>

</div>